### ISSUE TITLE
Only 50 results

### ISSUE THREAD

**Issue by zpelechova** [tugkan/dnb-scraper#1]
When url of a category on input, it only returns results from one page, doesnt go further.
https://my.apify.com/view/runs/bjuT8NMrzpn5Ohp42

**Comment by tugkan** [comment]
@zpelechova Hey there. You can use the newest version (0.0.8) for tackling with this problem. Please keep in mind that the `startUrls` attribute is now changed to string array. You can check the example usage from the default list.
